/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

	private static final Logger log = LoggerFactory.getLogger(KafkaBridge1.class);

	public static void main(String[] args) {

		//log.info("Entering main method");
		
		MQTTConnect1 m1 = new MQTTConnect1();
		m1.start();		
		//log.info("m1 started>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
		MQTTConnect2 m2 = new MQTTConnect2();
		m2.start();		
		//log.info("m2 started>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
		MQTTConnect3 m3 = new MQTTConnect3();
		m3.start();		
		//log.info("m2 started>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
		MQTTConnect4 m4 = new MQTTConnect4();
		m4.start();		
		//log.info("m2 started>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
		MQTTConnect5 m5 = new MQTTConnect5();
		m5.start();
		//log.info("m2 started>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
		
		//log.info("Exiting main method");

	}

}
